#!/usr/bin/env bash
# Migration script to modular zsh configuration

set -e

echo "=== Migrating to Modular Zsh Configuration ==="
echo

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Backup function
backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        local backup="${file}.bak.$(date +%Y%m%d_%H%M%S)"
        cp "$file" "$backup"
        echo -e "${GREEN}✓${NC} Backed up $file to $backup"
    fi
}

# Step 1: Backup existing configuration
echo "Step 1: Backing up existing configuration..."
backup_file ~/.zshrc
backup_file ~/naviscripts/src/zshrc
echo

# Step 2: Test the modular configuration
echo "Step 2: Testing modular configuration..."
if zsh -c "source ~/naviscripts/src/zshrc_modular; echo 'Config loads successfully'"; then
    echo -e "${GREEN}✓${NC} Modular configuration loads without errors"
else
    echo -e "${RED}✗${NC} Error loading modular configuration"
    echo "Please check the configuration and try again"
    exit 1
fi
echo

# Step 3: Ask user to test
echo "Step 3: Manual testing"
echo -e "${YELLOW}Please open a new terminal and run:${NC}"
echo "  source ~/naviscripts/src/zshrc_modular"
echo
echo "Test that:"
echo "  - Your prompt looks correct"
echo "  - Aliases work (try 'll' or 'gs')"
echo "  - Completions work (try 'git <TAB>' or 'cargo <TAB>')"
echo
read -p "Does everything work correctly? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Migration cancelled. Your original configuration is unchanged."
    exit 0
fi
echo

# Step 4: Create new .zshrc that uses modular config
echo "Step 4: Creating new .zshrc..."
cat > ~/.zshrc.new << 'EOF'
# Zsh configuration - loads modular configuration from naviscripts
# Generated by migrate_to_modular.sh

# Load the modular configuration
source ~/naviscripts/src/zshrc_modular

# Any machine-specific overrides can go in ~/.zshrc_local
EOF

echo -e "${GREEN}✓${NC} Created ~/.zshrc.new"
echo

# Step 5: Final confirmation
echo "Step 5: Final migration"
echo -e "${YELLOW}This will replace your .zshrc with the modular loader.${NC}"
echo "Your original .zshrc has been backed up."
read -p "Proceed with migration? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    mv ~/.zshrc.new ~/.zshrc
    echo -e "${GREEN}✓${NC} Migration complete!"
    echo
    echo "Your zsh configuration is now modular!"
    echo "  - Modules are in: ~/naviscripts/src/zsh/"
    echo "  - Main config: ~/naviscripts/src/zshrc_modular"
    echo "  - Local overrides: ~/.zshrc_local"
    echo
    echo "To customize:"
    echo "  - Edit modules in ~/naviscripts/src/zsh/"
    echo "  - Add local settings to ~/.zshrc_local"
    echo "  - Copy 99-local.zsh.template for machine-specific settings"
else
    rm ~/.zshrc.new
    echo "Migration cancelled. Your original configuration is unchanged."
fi