#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT="git@github.com:navicore"
UPSTREAM_ROOT="git@github.com:tableco"

REPOS=( 
        authsvc 
        chippendale 
        collectionsvc 
        contactsvc 
        devicesvc 
        devops 
        ernest 
        expertisesvc 
        frank 
        junebug 
        mailsvc 
        membersvc 
        messagesvc 
        notificationsvc 
        piecesvc 
        postalsvc 
        presencesvc 
        profilesvc 
        projectsvc 
        reviewsvc 
        roomsvc 
        tablelib 
        tablesvc 
        tfetable 
        tfeturntable 
        ui
      )

for repo in "${REPOS[@]}"
do
  repo_loc=$ROOT/$repo
  upstream_loc=$UPSTREAM_ROOT/$repo
  echo "cloning $repo"
  cd $DIR && git clone $repo_loc && cd $DIR/$repo && git remote add upstream $upstream_loc
done

