platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='osx'
fi

export LANG=en_US.UTF-8

export PATH="/usr/local/sbin:/usr/local/bin:$HOME/bin:$PATH"

ulimit -n 4096
BLOCKSIZE=K;	export BLOCKSIZE
VISUAL=vi;    export VISUAL
set -o vi
PAGER=more; export PAGER
EDITOR=vim; export EDITOR

alias busybox='kubectl run -i --tty $USER-busybox --image=busybox --restart=Never -- sh'
alias centos='kubectl run -i --tty $USER-centos --image=centos --restart=Never -- sh'
alias alpine='kubectl run -i --tty $USER-alpine --image=alpine --restart=Never -- sh'
alias ubuntu='kubectl run -i --tty $USER-ubuntu --image=ubuntu --restart=Never -- sh'
alias vim='nvim'
alias vim8='/usr/local/bin/vim'
alias vi='nvim'
alias l='exa'
alias ll='exa -l --header --git'
alias iex='rlwrap -a foo iex'
alias sz='source ~/.zshrc'
alias uvim='vim -u NONE'

alias kbb='kubectl run -it busybox --image=busybox -- sh'
alias k='kubectl'
alias dockerrm='docker rm $(docker ps -a -q)'
alias dockerstop='docker stop $(docker ps -a -q)'
alias dockerkill='docker kill $(docker ps -a -q)'
alias dockerrmi='docker rmi $(docker images -q)'
alias dockerrmif='docker rmi -f $(docker images -q)'
alias dockeruntagged='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias dockerdangle='docker rmi $(docker images -q --filter dangling=true)'

alias fetchupstream='git fetch upstream'
alias mergeupstream='git merge upstream/master'

export TERM="screen-256color"
export GIT_EDITOR="vim -f"

export HISTFILE=~/.zsh_history
export HISTSIZE=999999
export SAVEHIST=1000

setopt APPEND_HISTORY

if [[ $platform == 'linux' ]]; then
  export JAVA_HOME=$(dirname $(dirname $(readlink -f /usr/bin/java)))/..
elif [[ $platform == 'osx' ]]; then
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
  export JAVA_HOME="$(/usr/libexec/java_home)"
  export PATH="$PATH:/usr/local/texlive/2016/bin/x86_64-darwin"
fi 

# fix ^M issue in sbt interactive mode
stty icrnl

#
# Custom Cloud Theme with insane git prompt (really, I just want separate dirty and untracked indicators)
#

if [[ -z $ZSH_THEME_CLOUD_PREFIX ]]; then
    ZSH_THEME_CLOUD_PREFIX='☁'
fi

PROMPT_PRE=''
if [[ $platform == 'linux' ]]; then
  PROMPT_PRE='%n@%m'
else
  # see instructions at https://github.com/olivierverdier/zsh-git-prompt
  GIT_PROMPT_EXECUTABLE="haskell"
fi

source ~/tmp/zsh-git-prompt/zshrc.sh
PROMPT='${PROMPT_PRE}%{$fg_bold[cyan]%}$ZSH_THEME_CLOUD_PREFIX %{$fg[green]%}%p %{$fg[green]%}%c %{$fg[cyan]%}$(git_super_status)%{$fg_bold[blue]%}% %{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[cyan]%}["
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg_bold[cyan]%}] "

ZSH_THEME_GIT_PROMPT_SEPARATOR=""
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg[green]%}"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[blue]%}%{ ●%G%}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{ ✖%G%}"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[gray]%}%{ ✚%G%}"
ZSH_THEME_GIT_PROMPT_BEHIND="%{ ↓%G%}"
ZSH_THEME_GIT_PROMPT_AHEAD="%{ ↑%G%}"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg_bold[red]%}%{ …%G%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""

alias iexvi='rlwrap -a foo iex'

export GOPATH=~/go

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "caarlos0/git-add-remote"
# zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/mix",   from:oh-my-zsh
#zplug "plugins/helm",   from:oh-my-zsh
zplug "plugins/cargo",   from:oh-my-zsh
zplug "plugins/vi-mode",   from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# unsure why ohmy doesn't load
if [ $commands[helm] ]; then
  source <(helm completion zsh)
fi

autoload -U +X bashcompinit; bashcompinit
eval "$(register-python-argcomplete az)"

source $HOME/.cargo/env

if [ -f ~/.zshrc_local ]; then
  . ~/.zshrc_local
fi

export PYTHON_CONFIGURE_OPTS="--enable-framework"

export PATH="$PATH:$HOME/.local/bin"
export PIP_SHIMS_BASE_MODULE=pipenv.patched.notpip

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

export PATH=$PATH:/usr/local/go/bin:$HOME/.local/bin

if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi
