platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='osx'
fi

export PATH="/usr/local/sbin:/usr/local/bin:$HOME/bin:$PATH:$HOME/.local/bin"

ulimit -n 4096
BLOCKSIZE=K;	export BLOCKSIZE
VISUAL=vi;    export VISUAL
set -o vi
PAGER=more; export PAGER
EDITOR=vim; export EDITOR

alias dockerrm='docker rm $(docker ps -a -q)'
alias dockerstop='docker stop $(docker ps -a -q)'
alias dockerkill='docker kill $(docker ps -a -q)'
alias dockerrmi='docker rmi $(docker images -q)'
alias dockerrmif='docker rmi -f $(docker images -q)'
alias dockeruntagged='docker rmi $(docker images | grep "^<none>" | awk "{print $3}")'
alias dockerdangle='docker rmi $(docker images -q --filter dangling=true)'

alias fetchupstream='git fetch upstream'
alias mergeupstream='git merge upstream/master'

export TERM="screen-256color"
export GIT_EDITOR="vim -f"

setopt APPEND_HISTORY

autoload bashcompinit
bashcompinit

source ~/.antigen/antigen.zsh
antigen use oh-my-zsh

if [[ $platform == 'linux' ]]; then
  antigen theme cloud
  source <(kubectl completion zsh)
elif [[ $platform == 'osx' ]]; then
  antigen bundle brew
  source <(kubectl completion zsh)
  antigen theme cloud
fi 

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle sbodiu-pivotal/fly-zsh-autocomplete-plugin
antigen bundle caarlos0/git-add-remote
antigen bundle git
antigen bundle vi-mode
antigen bundle docker

# Tell antigen that you're done.
antigen apply

if [[ $platform == 'linux' ]]; then
  export JAVA_HOME=$(dirname $(dirname $(readlink -f /usr/bin/java)))/..
elif [[ $platform == 'osx' ]]; then
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
  export JAVA_HOME="$(/usr/libexec/java_home)"
  export PATH="$PATH:/usr/local/texlive/2016/bin/x86_64-darwin"
fi 

if [ -f ~/.zshrc_local ]; then
  . ~/.zshrc_local
fi

# fix ^M issue in sbt interactive mode
stty icrnl

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


if [[ -z $ZSH_THEME_CLOUD_PREFIX ]]; then
    ZSH_THEME_CLOUD_PREFIX='☁'
fi

PROMPT='%{$fg_bold[cyan]%}$ZSH_THEME_CLOUD_PREFIX %{$fg_bold[green]%}%p %{$fg[green]%}%c %{$fg_bold[cyan]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}[%{$fg[cyan]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}] %{$fg[yellow]%}⚡ %{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[green]%}]"

